import { Dimensions, Platform, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

const isSmallPhone = width < 375;
const isTablet = width >= 768;

export const responsive = {
  cardMaxWidth: isTablet ? 480 : ("100%" as const),
  paddingH: isTablet ? 40 : isSmallPhone ? 16 : 24,
  paddingV: isTablet ? 60 : isSmallPhone ? 28 : 40,
  cardPadding: isTablet ? 40 : isSmallPhone ? 20 : 28,
  cardRadius: isTablet ? 28 : 24,
  inputHeight: isSmallPhone ? 48 : 54,
  buttonHeight: isSmallPhone ? 48 : 54,
  titleSize: isTablet ? 36 : isSmallPhone ? 26 : 30,
  subtitleSize: isTablet ? 16 : 14,
  labelSize: isTablet ? 13 : 12,
  inputFontSize: isTablet ? 16 : 15,
  buttonFontSize: isTablet ? 17 : 16,
  avatarSize: isTablet ? 100 : isSmallPhone ? 68 : 80,
  avatarRadius: isTablet ? 32 : 28,
  avatarFontSize: isTablet ? 36 : isSmallPhone ? 24 : 28,
  fieldGapTop: isSmallPhone ? 12 : 16,
  buttonMarginTop: isSmallPhone ? 20 : 28,
};

export const colors = {
  primary: "#2563EB",
  primaryDark: "#1D4ED8",
  primaryLight: "#EFF6FF",
  accent: "#FF6584",
  success: "#2DD4BF",
  bg: "#F7F8FC",
  surface: "#FFFFFF",
  border: "#E8EAF0",
  borderFocus: "#2563EB",
  textPrimary: "#1A1D2E",
  textSecondary: "#6B7080",
  textMuted: "#A0A5B8",
  error: "#FF4D6D",
  errorBg: "#FFF0F3",
  shadow: "#2563EB",
};

export const globalStyles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: responsive.paddingH,
    backgroundColor: colors.bg,
  },
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: colors.bg,
  },
  innerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: responsive.paddingH,
    paddingVertical: responsive.paddingV,
    width: "100%",
  },
  card: {
    width: "100%",
    maxWidth: responsive.cardMaxWidth,
    backgroundColor: colors.surface,
    borderRadius: responsive.cardRadius,
    padding: responsive.cardPadding,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
    alignSelf: "center",
  },
  title: {
    fontSize: responsive.titleSize,
    fontWeight: "800",
    color: colors.textPrimary,
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: responsive.subtitleSize,
    color: colors.textSecondary,
    marginBottom: isSmallPhone ? 20 : 28,
    lineHeight: isTablet ? 24 : 20,
  },
  fieldLabel: {
    fontSize: responsive.labelSize,
    fontWeight: "700",
    color: colors.textSecondary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 8,
    marginTop: responsive.fieldGapTop,
    alignSelf: "flex-start",
    width: "100%",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surface,
    width: "100%",
    height: responsive.inputHeight,
    paddingHorizontal: 16,
  },
  inputWrapperFocused: {
    borderColor: colors.borderFocus,
    borderWidth: 2,
    backgroundColor: colors.primaryLight,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },
  textInput: {
    flex: 1,
    height: "100%",
    fontSize: responsive.inputFontSize,
    color: colors.textPrimary,
    ...Platform.select({
      web: {
        outlineStyle: "none",
        outlineWidth: 0,
      } as any,
    }),
  },
  iconContainer: {
    padding: 6,
  },
  button: {
    width: "100%",
    height: responsive.buttonHeight,
    borderRadius: 14,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    marginTop: responsive.buttonMarginTop,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  buttonText: {
    color: colors.surface,
    fontWeight: "700",
    fontSize: responsive.buttonFontSize,
    letterSpacing: 0.3,
  },
  dangerButton: {
    width: "100%",
    height: responsive.buttonHeight,
    borderRadius: 14,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#FFD6DC",
    flexDirection: "row",
    gap: 8,
  },
  dangerButtonText: {
    color: colors.error,
    fontWeight: "700",
    fontSize: responsive.buttonFontSize,
  },
  linkButton: {
    marginTop: isSmallPhone ? 14 : 20,
    paddingVertical: 4,
  },
  linkText: {
    color: colors.textSecondary,
    fontSize: isTablet ? 15 : 14,
    textAlign: "center",
  },
  linkTextBold: {
    color: colors.primary,
    fontWeight: "700",
  },
  errorContainer: {
    width: "100%",
    backgroundColor: colors.errorBg,
    borderRadius: 12,
    padding: isSmallPhone ? 10 : 12,
    borderLeftWidth: 4,
    borderLeftColor: colors.error,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  errorText: {
    color: colors.error,
    fontSize: isTablet ? 14 : 13,
    fontWeight: "500",
    flex: 1,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: colors.border,
    marginVertical: isSmallPhone ? 14 : 20,
  },
});
